project_name: version-bumper

builds:
  - binary: version-bumper
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

brews:
  - name: version-bumper
    repository:
      owner: tamasmarton
      name: homebrew-tap
      branch: main
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    description: "CLI tool to bump package.json version and commit it"
    homepage: "https://github.com/tamasmarton/go-version-bumper"
    license: "MIT"

release:
  github:
    owner: tamasmarton
    name: go-version-bumper
  draft: false
  prerelease: ""
